language: node_js
node_js: 8.5.0
install: yarn
jobs:
  include:
    - stage: build
      script: 
        yarn lint &&
        yarn test
    - stage: deploy
      if: branch = master
      script: yarn test