language: node_js
node_js: 8.5.0
before_install:
  - openssl aes-256-cbc -K $encrypted_e47b4d652ad1_key -iv $encrypted_e47b4d652ad1_iv -in production.zip.enc -out app_configuration/environments/production.zip -d
  - unzip production.zip
install: yarn
jobs:
  include:
  - stage: Build
    script: 
      unzip production.zip &&
      yarn job production &&
      yarn lint && 
      yarn test
  - stage: Build Android 🤖
    if: branch = master OR branch = develop
    language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - platform-tools
        - android-28
        - extra-google-m2repository
        - extra-google-google_play_services
    before_install:
      - nvm install 8.5.0
      - gem install bundler
      - bundle install
    env: 
      - SUPPLY_PACKAGE_NAME="com.reactnative.starterkit"
    script: yarn android:build