language: node_js
node_js: 8.5.0
install: yarn
script: yarn lint && yarn test
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test
    - stage: build
      script: yarn lint
    - stage: deploy
      if: branch = master
      script: yarn test