branches:
  only:
  - master
  - develop
  - playstore-alpha
  - testflight
install: yarn
after_install: 
  - openssl aes-256-cbc -K $encrypted_e47b4d652ad1_key -iv $encrypted_e47b4d652ad1_iv -in production.zip.enc -out production.zip -d
  - unzip -o production.zip
  - yarn job production
jobs:
  include:
  - stage: Lint & Test
    if: branch = master OR branch = develop
    language: node_js
    node_js: 8.5.0
    script: 
      yarn lint && 
      yarn test
  - stage: Build iOS
    if: branch = master OR branch = develop
    language: node_js
    node_js: 8.5.0
    os: osx
    osx_image: xcode10.2
    before_install: 
      - bundle install
    script: 
      cd ios && pod install --repo-update && cd .. &&
      yarn ios:build
  - stage: Release iOS to Testflight
    if: branch = testflight
    language: node_js
    node_js: 8.5.0
    os: osx
    osx_image: xcode10.2
    before_install: 
      - bundle install
    script: 
      # itms is needed, otherwise altool will not work correctly
      cd ios && pod install --repo-update && cd .. &&
      yarn ios:build &&
      ln -s "/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool" /usr/local/bin/altool &&
      ln -s "/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms" /usr/local/bin/itms &&
      altool --upload-app -f "mobile.ipa" -u $PILOT_USERNAME -p $FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
  - stage: Build Android
    if: branch = master OR branch = develop
    language: android
    jdk: oraclejdk8
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-28
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
    before_install:
      - nvm install 8.5.0
      - gem install bundler
      - bundle install
      # https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not-b
      - mkdir "$ANDROID_HOME/licenses" || true
      - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
    install: yarn
    before_script:
      # https://github.com/wix/react-native-interactable/issues/146
      - cd node_modules/react-native-interactable
      - rm -rf \{ios\,android\} && rm -rf android && rm -rf ios
      - ln -s lib/android . && ln -s lib/ios .
      - cd ../..
    script: 
      yarn android:build
  - stage: Release Android to Alpha
    if: branch = playstore-alpha
    language: android
    jdk: oraclejdk8
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-28
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
    before_install:
      - nvm install 8.5.0
      - gem install bundler
      - bundle install
      # https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not-b
      - mkdir "$ANDROID_HOME/licenses" || true
      - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
    install: yarn
    before_script:
      # https://github.com/wix/react-native-interactable/issues/146
      - cd node_modules/react-native-interactable
      - rm -rf \{ios\,android\} && rm -rf android && rm -rf ios
      - ln -s lib/android . && ln -s lib/ios .
      - cd ../..
    script: 
      yarn android:alpha