jobs:
  include:
  # - stage: Build
  #   script: 
  #     unzip -o production.zip &&
  #     yarn job production &&
  #     yarn lint && 
  #     yarn test
  - stage: Build Android 🤖
    if: branch = master OR branch = develop
    language: android
    jdk: oraclejdk8
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-28
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
    before_install:
      - nvm install 8.5.0
      - gem install bundler
      - bundle install
      # https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not-b
      - mkdir "$ANDROID_HOME/licenses" || true
      - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
      - openssl aes-256-cbc -K $encrypted_e47b4d652ad1_key -iv $encrypted_e47b4d652ad1_iv -in production.zip.enc -out production.zip -d
      - unzip production.zip
    env: 
      - SUPPLY_PACKAGE_NAME="com.reactnative.starterkit"
    install: yarn
    before_script:
      # https://github.com/wix/react-native-interactable/issues/146
      - cd node_modules/react-native-interactable
      - rm -rf \{ios\,android\} && rm -rf android && rm -rf ios
      - ln -s lib/android . && ln -s lib/ios .
    script: 
      yarn job production &&
      yarn lint && 
      yarn android:build