# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/Performance', '~> 5.20.1'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'FBSDKCoreKit', '~> 4.39.1'
  pod 'FBSDKLoginKit', '~> 4.39.1'
  pod 'FBSDKShareKit', '~> 4.39.1'
  pod 'GoogleSignIn', '~> 4.4.0'
  
  # IMPORTANT: do not use 3rd react-related pods here since we don't use pod to manage React native

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  # pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  # pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
  # pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'
  # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # target 'mobileTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

target 'mobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile-tvOS

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
