# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do

  desc 'Build the Android application.'
  lane :build do |options|
    gradle(task: 'clean', project_dir: 'android/')
    gradle(
      task: 'assemble', 
      build_type: 'Release', 
      project_dir: 'android/',
    )
 
  end

  desc 'Ship to Playstore Alpha.'
  lane :alpha do |options|
    build
    upload_to_play_store(
      track: 'alpha',
      json_key: 'fastlane/googlePlaySecretKey.json'
    )
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do |options|
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: "beta",
      json_key: 'fastlane/googlePlaySecretKey.json'
    )
  end

  desc 'Ship to Playstore Production.'
  lane :production do |options|
    upload_to_play_store(
      track: 'beta',
      track_promote_to: "production",
      json_key: 'fastlane/googlePlaySecretKey.json'
    )
  end
end

platform :ios do
  # iOS Lanes
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(
      readonly: true, 
      type: 'appstore',
      storage_mode: 'git'
    )
  end

  desc 'Build the iOS application.'
  lane :build do
    certificates
    gym(
      scheme: 'mobile', 
      workspace: './ios/mobile.xcworkspace', 
      include_bitcode: true
    )
  end

  desc 'Ship to Appstore Testflight.'
  lane :uploadToTestflight do
    build
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  desc 'Ship to Appstore Production.' 
  lane :production do
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification,
      skip_binary_upload: true
    )
  end
end
